In [1]:
import bert_score
from deepeval.metrics import GEval
from deepeval.test_case import LLMTestCase, LLMTestCaseParams
import matplotlib.pyplot as plt
import os
import pandas as pd
import pprint
from sklearn import metrics
import urllib

from deepeval.models import AmazonBedrockModel

import boto3
from pydantic_ai.models.bedrock import BedrockConverseModel
from pydantic_evals import Dataset, Case
from pydantic_evals.evaluators import LLMJudge
from pydantic_ai.settings import ModelSettings

from ragas.metrics import SummarizationScore
from ragas import EvaluationDataset, evaluate as ragas_evaluate
from langchain_aws import ChatBedrockConverse, BedrockEmbeddings
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

/tmp/ipykernel_10881/1363130716.py:19: DeprecationWarning: Importing SummarizationScore from 'ragas.metrics' is deprecated and will be removed in v1.0. Please use 'ragas.metrics.collections' instead. Example: from ragas.metrics.collections import SummarizationScore
  from ragas.metrics import SummarizationScore

In [2]:
import nest_asyncio
nest_asyncio.apply()

In [3]:
settings={}
settings["n_prompts"] = 30
settings["region"] = "eu-west-2"
settings["temperatures"] = [0, 0.1, 0.2]
settings["max_tokens"] = 4096
settings["threshold"] = 0.7

In [4]:
models = {}

models['Claude 3 Haiku'] = 'anthropic.claude-3-haiku-20240307-v1:0'
#models['Claude 3 Sonnet'] = 'anthropic.claude-3-sonnet-20240229-v1:0'
models['Claude 3.7 Sonnet'] = 'anthropic.claude-3-7-sonnet-20250219-v1:0'
models['GPT OSS 20b'] = "openai.gpt-oss-20b-1:0"
models['GPT OSS 120b'] = "openai.gpt-oss-120b-1:0"

## Set Environment Variables

In [5]:
os.environ["AWS_DEFAULT_REGION"] = settings["region"]

## Get Data

In [6]:
datasets = [
    'https://huggingface.co/datasets/EdinburghNLP/xsum/resolve/main/data/validation-00000-of-00001.parquet',
    'https://raw.githubusercontent.com/sylinrl/TruthfulQA/main/data/v1/TruthfulQA.csv'
   ]

In [7]:
for directory in ['data', 'output']:
    if not os.path.exists(directory):
        os.makedirs(directory)
    
for dataset in datasets:
    print(dataset)
    filename=dataset.split('/')[-1]
    if not os.path.isfile(f'data/{filename}'):
        print(f'downloading {filename}')
        urllib.request.urlretrieve(dataset, f'data/{filename}')

https://huggingface.co/datasets/EdinburghNLP/xsum/resolve/main/data/validation-00000-of-00001.parquet
https://raw.githubusercontent.com/sylinrl/TruthfulQA/main/data/v1/TruthfulQA.csv

## Summary Data

In [8]:
summary_df = pd.read_parquet('data/validation-00000-of-00001.parquet')
summary_df

,document,summary,id
0,The ex-Reading defender denied fraudulent trad...,Former Premier League footballer Sam Sodje has...,38295789
1,Voges was forced to retire hurt on 86 after su...,Middlesex batsman Adam Voges will be out until...,40202028
2,Seven photographs taken in the Norfolk country...,The Duchess of Cambridge will feature on the c...,36177725
3,"Chris Poole - known as ""moot"" online - created...",Google has hired the creator of one of the web...,35751255
4,Four police officers were injured in the incid...,Two teenagers have been charged in connection ...,35275743
...,...,...,...
11327,Phyllida Lloyd will direct revivals of Julius ...,London's Donmar Warehouse is to open a tempora...,36376969
11328,The decision came after the governor of Rio de...,The government in Brazil says it will send fed...,26691258
11329,The deal will create the second largest cable ...,The US Department of Justice (DoJ) has approve...,36133259
11330,Third seed Murray beat Czech eighth seed Tomas...,Britain's Andy Murray will face world number o...,32178027
11331,"So far, more than 3,500 have been assessed and...",The States of Guernsey planning department has...,30562818

In [9]:
summary_correct_df = summary_df.copy()
summary_correct_df['is_correct'] = True

summary_incorrect_df = summary_df.copy()
summary_incorrect_df["summary"] = summary_incorrect_df["summary"].sample(frac=1).values
summary_incorrect_df['is_correct'] = False

summary_evaluate_df = pd.concat([summary_correct_df, summary_incorrect_df])
summary_evaluate_df.reset_index(drop=True)
summary_evaluate_df

,document,summary,id,is_correct
0,The ex-Reading defender denied fraudulent trad...,Former Premier League footballer Sam Sodje has...,38295789,True
1,Voges was forced to retire hurt on 86 after su...,Middlesex batsman Adam Voges will be out until...,40202028,True
2,Seven photographs taken in the Norfolk country...,The Duchess of Cambridge will feature on the c...,36177725,True
3,"Chris Poole - known as ""moot"" online - created...",Google has hired the creator of one of the web...,35751255,True
4,Four police officers were injured in the incid...,Two teenagers have been charged in connection ...,35275743,True
...,...,...,...,...
11327,Phyllida Lloyd will direct revivals of Julius ...,Facebook says it is investigating a mother's c...,36376969,False
11328,The decision came after the governor of Rio de...,A French police officer is in a life-threateni...,26691258,False
11329,The deal will create the second largest cable ...,The International Cricket Council will not sen...,36133259,False
11330,Third seed Murray beat Czech eighth seed Tomas...,Dozens of people have been killed in suicide a...,32178027,False
11331,"So far, more than 3,500 have been assessed and...",Scientists in Spain have received funding to t...,30562818,False

In [10]:
settings["model_id"]='anthropic.claude-3-haiku-20240307-v1:0'
settings["model_name"]='Claude 3 Haiku'
settings["temperature"] = 0

row = summary_evaluate_df.head(1).to_dict('records')[0]
row

{'document': 'The ex-Reading defender denied fraudulent trading charges relating to the Sodje Sports Foundation - a charity to raise money for Nigerian sport.\nMr Sodje, 37, is jointly charged with elder brothers Efe, 44, Bright, 50 and Stephen, 42.\nAppearing at the Old Bailey earlier, all four denied the offence.\nThe charge relates to offences which allegedly took place between 2008 and 2014.\nSam, from Kent, Efe and Bright, of Greater Manchester, and Stephen, from Bexley, are due to stand trial in July.\nThey were all released on bail.',
 'summary': 'Former Premier League footballer Sam Sodje has appeared in court alongside three brothers accused of charity fraud.',
 'id': '38295789',
 'is_correct': True}

## DeepEval

In [11]:
def connect_to_bedrock(settings):
    bedrock_model = AmazonBedrockModel(
        model=settings["model_id"],
        region=settings["region"],
        generation_kwargs={
            "temperature": settings["temperature"],
            "maxTokens": settings["max_tokens"]
        }
    )
    return bedrock_model
#bedrock_model = connect_to_bedrock(settings)

In [12]:
def evaluate_summary_deepeval(bedrock_model, document: str, summary: str, settings: dict):
    
    summarisation_metric = GEval(
        name="Summarization Quality",
        criteria="Summarization Quality: Evaluate if the summary is a concise, faithful, and coherent representation of the source document.",
        evaluation_params=[
            LLMTestCaseParams.INPUT, 
            LLMTestCaseParams.ACTUAL_OUTPUT
        ],
        model=bedrock_model,
        threshold=settings["threshold"],
        async_mode=False
    )

    test_case = LLMTestCase(
        input=document,
        actual_output=summary
    )
    
    summarisation_metric.measure(test_case)

    return {
        'function': 'Summary', 
        'method': 'Deepeval',
        'score': summarisation_metric.measure(test_case),
        'passed': summarisation_metric.is_successful()
    }


#evaluation = evaluate_summary_deepeval(bedrock_model, row["document"], row["summary"], settings)
#evaluation

## Pydantic

In [13]:
def evaluate_summary_pydantic(document: str, summary: str, settings: dict): 
    judge_llm = BedrockConverseModel(settings["model_id"])

    judge = LLMJudge(
        model=judge_llm,
        rubric="""
        You will be given a SOURCE DOCUMENT and a SUMMARY. Your task is to score the SUMMARY
        against the SOURCE DOCUMENT on a scale from 0.0 to 1.0.
        
        Evaluate on three criteria:
        1. Faithfulness (most important): Does the summary contain ONLY information from the source?
           Any hallucinated or fabricated content should heavily penalise the score.
        2. Coverage: Does the summary capture the key points from the source?
        3. Conciseness: Is the summary shorter than the source without losing critical detail?
        
        Scoring guide:
        - 1.0: Fully faithful, covers all key points, appropriately concise
        - 0.7-0.9: Minor omissions or slight wordiness, no hallucinations
        - 0.4-0.6: Some missed key points OR minor hallucinations
        - 0.1-0.3: Major hallucinations OR misses most key points
        - 0.0: Completely fabricated or wholly irrelevant
        
        IMPORTANT: Hallucinations must always result in a score below 0.5, regardless of
        how well-written the summary appears.
        """,
        score={'evaluation_name': 'SummaryQualityScore'},
        model_settings=ModelSettings(
            temperature=settings["temperature"],
            max_tokens=settings["max_tokens"]
        ),
        include_input=True,
        include_expected_output=False,
    )

    dataset = Dataset(
        cases=[Case(inputs=document)],
        evaluators=[judge],
    )

    print("Case input:", dataset.cases[0].inputs)

    report = dataset.evaluate_sync(lambda x: summary)
    score = report.cases[0].scores['SummaryQualityScore'].value
    reason = report.cases[0].assertions.get('LLMJudge_pass').reason

    return {
        'function': 'Summary',
        'method': 'Pydantic',
        'score': score,
        'reason': reason,
        'passed': bool(score >= settings["threshold"])
    }

#evaluation = evaluate_summary_pydantic(row["document"], row["summary"], settings)
#evaluation

In [14]:
row

{'document': 'The ex-Reading defender denied fraudulent trading charges relating to the Sodje Sports Foundation - a charity to raise money for Nigerian sport.\nMr Sodje, 37, is jointly charged with elder brothers Efe, 44, Bright, 50 and Stephen, 42.\nAppearing at the Old Bailey earlier, all four denied the offence.\nThe charge relates to offences which allegedly took place between 2008 and 2014.\nSam, from Kent, Efe and Bright, of Greater Manchester, and Stephen, from Bexley, are due to stand trial in July.\nThey were all released on bail.',
 'summary': 'Former Premier League footballer Sam Sodje has appeared in court alongside three brothers accused of charity fraud.',
 'id': '38295789',
 'is_correct': True}

## Ragas

In [15]:
def evaluate_summary_ragas(document: str, summary: str, settings: dict):
    langchain_llm = ChatBedrockConverse(
        model_id=settings["model_id"],
        region_name=settings["region"],
        temperature=settings["temperature"]
    )
    
    ragas_llm = LangchainLLMWrapper(langchain_llm)

    metric = SummarizationScore(llm=ragas_llm)

    dataset = EvaluationDataset.from_list([{
        "user_input": document,
        "response": summary,
        "reference_contexts": [document]
    }])

    score = ragas_evaluate(dataset=dataset, metrics=[metric])["summary_score"][0]
    
    return {
        'function': 'Summary',
        'method': 'Ragas',
        'score': score,
        'passed': bool(score >= settings["threshold"])
    }

#evaluation = evaluate_summary_ragas(row["document"], row["summary"], settings)
#evaluation

## Bert Score

In [16]:
def evaluate_summary_bert_score(document, summary, settings):
    p, r, f1 = bert_score.score(
        [document],
        [summary],
        model_type=settings["model_id"],
        verbose=False
    )

    return {
        'function': 'Summary',
        'method': 'Bert Score',
        'score': f1[0].item(),
        'passed': bool(f1[0].item() >= settings["threshold"])
    }

#evaluation = evaluate_summary_bert_score(row["document"], row["summary"], settings)
#evaluation

## Evaluate All Methods

In [ ]:
summary_sample_df = summary_evaluate_df.sample(settings["n_prompts"])
evaluations = []

# Deepeval (LLM as as Judge)
for model_name, model_id in models.items():
    settings["model_name"] = model_name
    settings["model_id"] = model_id

    for temperature in settings["temperatures"]:
        print(f"evaluating deepeval using {model_name} at temperature {temperature}")
        settings["temperature"] = temperature

        bedrock_model = connect_to_bedrock(settings)
    
        for row in summary_sample_df.to_dict('records'):     
            try:
                evaluation = evaluate_summary_deepeval(bedrock_model, row["document"], row["summary"], settings)
                evaluations.append(row | settings | evaluation)
            except:
                pass
        
        pd.DataFrame(evaluations).to_csv('output/summary_evaluations.csv', index=False)

# Pydantic (LLM as as Judge)
for model_name, model_id in models.items():
    settings["model_name"] = model_name
    settings["model_id"] = model_id

    for temperature in settings["temperatures"]:
        print(f"evaluating pydantic using {model_name} at temperature {temperature}")
        settings["temperature"] = temperature

        for row in summary_sample_df.to_dict('records'):
            try:
                evaluation = evaluate_summary_pydantic(row["document"], row["summary"], settings)
                evaluations.append(row | settings | evaluation)
            except:
                pass
        
        pd.DataFrame(evaluations).to_csv('output/summary_evaluations.csv', index=False)

# Ragas
#settings["model_name"] = "Langchain"
#settings["model_id"] = "None"
for model_name, model_id in models.items():
    settings["model_name"] = model_name
    settings["model_id"] = model_id
    for temperature in settings["temperatures"]:
        for row in summary_sample_df.to_dict('records'):   
            try:
                evaluation = evaluate_summary_ragas(row["document"], row["summary"], settings)
                evaluations.append(row | settings | evaluation)
            except:
                pass
        
        pd.DataFrame(evaluations).to_csv('output/summary_evaluations.csv', index=False)

# Bert Score
settings["model_name"] = "Distilbert Base Uncased"
settings["model_id"] = "distilbert-base-uncased"
settings["temperature"] = "None"
print("evaluating bert score")
for row in summary_sample_df.to_dict('records'):
    try:
        evaluation = evaluate_summary_bert_score(row["document"], row["summary"], settings)
        evaluations.append(row | settings | evaluation)
    except:
        pass

evaluations_df = pd.DataFrame(evaluations)
evaluations_df.to_csv('output/summary_evaluations.csv', index=False)
evaluations_df

evaluating deepeval using Claude 3 Haiku at temperature 0

Output()

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x751dcc0bb740> is already entered

Exception in callback Task.__step()
handle: <Handle Task.__step()>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: cannot enter context: <_contextvars.Context object at 0x751dcc0bb740> is already entered

Task was destroyed but it is pending!
task: <Task pending name='Task-35' coro=<_async_in_context.<locals>.run_in_context() done, defined at
/home/iods/git/ai-spike-evaluation-metrics/.venv/lib/python3.12/site-packages/ipykernel/utils.py:57> wait_for=<Task
pending name='Task-36' coro=<Kernel.shell_main() running at
/home/iods/git/ai-spike-evaluation-metrics/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597>
cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at
/home/iods/git/ai-spike-evaluation-metrics/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>

/usr/lib/python3.12/json/decoder.py:353: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  obj, end = self.scan_once(s, idx)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-36' coro=<Kernel.shell_main() running at
/home/iods/git/ai-spike-evaluation-metrics/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597>
cb=[Task.__wakeup()]>

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x751bbf0c68a0>
Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x751bac75e810>, 3710.938519551)])']
connector: <aiohttp.connector.TCPConnector object at 0x751bbfb32330>

Output()

evaluating deepeval using Claude 3 Haiku at temperature 0.1

Task was destroyed but it is pending!
task: <Task pending name='Task-30' coro=<_async_in_context.<locals>.run_in_context() running at
/home/iods/git/ai-spike-evaluation-metrics/.venv/lib/python3.12/site-packages/ipykernel/utils.py:60> wait_for=<Task
pending name='Task-32' coro=<Kernel.shell_main() running at
/home/iods/git/ai-spike-evaluation-metrics/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597>
cb=[Task.__wakeup()]> cb=[ZMQStream._run_callback.<locals>._log_error() at
/home/iods/git/ai-spike-evaluation-metrics/.venv/lib/python3.12/site-packages/zmq/eventloop/zmqstream.py:563]>

/usr/lib/python3.12/asyncio/base_events.py:894: RuntimeWarning: coroutine 'Kernel.shell_main' was never awaited
  async def getaddrinfo(self, host, port, *,
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Task was destroyed but it is pending!
task: <Task pending name='Task-32' coro=<Kernel.shell_main() running at
/home/iods/git/ai-spike-evaluation-metrics/.venv/lib/python3.12/site-packages/ipykernel/kernelbase.py:597>
cb=[Task.__wakeup()]>

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x751bac7b7170>
Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x751bac641430>, 3898.843039413)])']
connector: <aiohttp.connector.TCPConnector object at 0x751bac68e810>

Output()

evaluating deepeval using Claude 3 Haiku at temperature 0.2

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x751bbf0c6420>
Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x751bbe606270>, 4083.781596035)])']
connector: <aiohttp.connector.TCPConnector object at 0x751bac7b5e80>

Output()

evaluating deepeval using Claude 3.7 Sonnet at temperature 0

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x751bbe5b6f60>
Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x751b5fc79250>, 4361.001508927)])']
connector: <aiohttp.connector.TCPConnector object at 0x751bbe58b620>

Output()

evaluating deepeval using Claude 3.7 Sonnet at temperature 0.1

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()

Output()